### ISSUE TITLE
Feedback épisode 1

### ISSUE THREAD

**Issue by tzi** [hteumeuleu/troisdoublev#1]
J'adore !

Tu m'as beaucoup fait rire :dancer: 
Voici les remarques que je me suis faites en lisant :

> Et le Web, c'est une application de ce réseau, au même titre que le courrier électronique ou le jeu en ligne.

Je trouve toujours ça un peu flou. Je dirais : "Le Web, c'est tout ce qui se passe dans un navigateur. C'est une application de ce réseau, au même titre que le courrier électronique ou le jeu en ligne."

> le résumé le plus concis que j'ai vu est celui donné par John Gruber

Je n'ai pas compris de quel résumé tu parles.

> Plateforme / Continuum

À mes étudiants je continue de définir le web comme ce qui se passe dans le navigateur. Mais je dis que les technologies qui ont fait le web (HTML / CSS) s'exporte désormais ailleurs. On peut faire des applications (avec Electron), un OS (Firefox OS), des livres papiers (epub), des présentations, etc.

> HTTP et HTML

C'est une remarque plus globale.
J'avais en tête que Tim avait créé à la fois HTTP et HTML, mais aussi le premier serveur web, et le premier navigateur web. Chaque maillon de cette chaîne ne serait pas utile sans tous les autres.
Je me serai attendue à une présentation courte du w3c, et au fait que toutes ces spécifications étaient ouvertes. Mais ça risque d'alourdir ton histoire.

Des bises,
Thomas.

**Comment by hteumeuleu** [comment]
Merci beaucoup pour tes retours Thomas !

> Je dirais : "Le Web, c'est tout ce qui se passe dans un navigateur. C'est une application de ce réseau, au même titre que le courrier électronique ou le jeu en ligne."

Quid des robots qui parcourent le Web ? Ils n'utilisent pas de navigateur. Mais pourtant ils vont bien aller chercher du HTML via HTTP (le Web, donc).

> Je n'ai pas compris de quel résumé tu parles.

Je le dis la phrase d'après : _Il appelle ça « les HTs: HTTP et HTML »_ Mais résumé n'est peut-être pas le bon mot. C'est plutôt une définition.

> Je me serai attendue à une présentation courte du w3c, et au fait que toutes ces spécifications étaient ouvertes. Mais ça risque d'alourdir ton histoire.

Effectivement. Mais ça pourrait faire l'objet d'un épisode dédié : c'est quoi le W3C, comment on participe à la construction des standards du Web, en quoi c'est différent d'autres plate-formes  langages, …

**Comment by tzi** [comment]
> Quid des robots qui parcourent le Web ? Ils n'utilisent pas de navigateur. Mais pourtant ils vont bien aller chercher du HTML via HTTP (le Web, donc).

J'aurais dit qu'ils avaient le rôle de navigateur aussi, puisqu'ils interprètent le HTML. Par exemple, Lynx est un navigateur web valide ? Mais c'est en effet une approximation pour rendre le concept plus compréhensible

> Je le dis la phrase d'après : Il appelle ça « les HTs: HTTP et HTML » Mais résumé n'est peut-être pas le bon mot. C'est plutôt une définition.

Ah. Alors, je n'ai pas compris l'intérêt de cette citation « les HTs: HTTP et HTML ». Je croyais que c'était le titre de se conférence. Je trouve plus simple de parler de HTTP et HTML, plutôt que de rajouter un nouveau nom peu connu, surtout que ce sont des choses très différentes.

> Effectivement. Mais ça pourrait faire l'objet d'un épisode dédié : c'est quoi le W3C

OK. Une petite phrase serait quand même utile pour relier le contenu de la vidéo avec le présent. Du style "Il a ensuite fonder une organisation pour gérer les évolutions du web. ça s'appelle le w3c et encore aujourd'hui Tim en est le président."

Ce ne sont toujours que des propositions :wink:

**Comment by hteumeuleu** [comment]
Oui mais c'est vraiment intéressant d'avoir ces retours ! Effectivement, une petite mention du W3C ne sera pas de trop. (Par contre, TimBL n'en est plus le CEO, c'est Jeff Jaffe depuis 2010. Et à vrai dire, je ne suis même pas sûr du rôle que tient encore TimBL au sein du W3C. À creuser !)

> Alors, je n'ai pas compris l'intérêt de cette citation « les HTs: HTTP et HTML ». Je croyais que c'était le titre de se conférence. Je trouve plus simple de parler de HTTP et HTML, plutôt que de rajouter un nouveau nom peu connu, surtout que ce sont des choses très différentes.

Je pense que ça passera mieux en vidéo. Et Gruber, c'est l'inventeur de Markdown donc pas non plus complètement un inconnu. Et c'est vraiment cette explication qui m'a fait « tilt » et m'a fait me rendre compte à quel point le web c'est vraiment HTML et HTTP (et pas HTML et CSS et JS comme je le comprenais auparavant).

**Comment by tzi** [comment]
> Et à vrai dire, je ne suis même pas sûr du rôle que tient encore TimBL au sein du W3C.

Si c'est vrai, alors les fiches Wikipedia de Tim et du w3c ne sont pas à jour : https://fr.wikipedia.org/wiki/World_Wide_Web_Consortium

> Et c'est vraiment cette explication qui m'a fait « tilt » et m'a fait me rendre compte à quel point le web c'est vraiment HTML et HTTP

Je comprends mieux. Il faudra bien faire attention à comment tu le présentes alors :)

**Comment by tzi** [comment]
Je viens de voir la vidéo finales, et c'est super !
