### ISSUE TITLE
Retours épisode 1

### ISSUE THREAD

**Issue by iamvdo** [hteumeuleu/troisdoublev#2]
Hello.

Alors déjà, j'adore l'idée, et j'aime beaucoup la vidéo pré-montée. Voici mes quelques remarques (plus sur la forme) qui sont souvent d'ailleurs plutôt des questions :)

Sur le fond, je n'ai pas grand chose à ajouter, je trouve ça super

(temps basé sur le 2e montage)

0:06, puis 0:24 je trouve perturbant le son du scroll de la souris qui n'est pas synchro sur le vrai défilement

0:24 ajoutez le texte "Ferranti Mark 1" ? Juste pour fixer ce qu'on vient d'entendre

0:40 problème de son ?

1:06 « et range ses petits fichiers dans son coin » j'adore le ton :)

1:50 carte (j'aurais bien fait figurer la frontière et le batiment 31 en plus marqué, pour bien voir). Je peux surement t'aider

2:40 tu dis en 2009 pour les 20 ans du web (mais c'est pas plutôt en 2014 pour les 20 ans du W3C/25 ans du Web?)

3:05 je trouve l'anim pas très en phase avec le propos. Tu survoles des navigateurs, puis l'appli mail, puis Photoshop

3:17 John Gruber (peut-être dire qui il est), et d'ailleurs pourquoi pas mettre les noms aussi à 2:57 ?

3:20 traduction FR en plus ?

3:42 pas d'illustrations ?

3:56 -> 4:04 vide ? du coup  est-ce utile ? ou dire qu'il y aura un épisode dédié ?

4:17 (idem 3:17 et 3:20)

5:00 c'est vrai que le mot continuum est un peu confus (mais on comprends bien le discours de Jeremy). Peux-être reprendre en français, le web est une continuité ?

5:30 le son clic mais il manque l'icone pause ?

5:50 après le «This is for everyone. C'est pour le tout le monde», j'aurais encore plus accentué, avec un « c'est de ça dont je parlais » ou un truc du genre pour faire référence à ton «c'est pas de ça dont je parlais » ironique qq secondes avant

Sinon, un point plus global, tu n'as pas mis de sons (musiques, ambiance), j'imagine que c'est volontaire, mais ça peut apporter un peu de dynamisme, notamment sur les passages sans illustrations. C'est quoi ton point de vue là-dessus ?

**Comment by hteumeuleu** [comment]
Waouh ! Merci pour toutes ces remarques. Alors, je retiens : 

* 0:06, puis 0:24 : son du scroll pas synchro. (Effectivement, maintenant que tu le dis ça me choque aussi.)
* 0:24 ajoutez le texte "Ferranti Mark 1"
* 1:50 carte (j'aurais bien fait figurer la frontière et le batiment 31 en plus marqué) : Yes c'était l'idée ! Faut que j'arrive à trouver comment faire ça dans Premiere. Si jamais tu sais ou tu as une autre suggestion, je suis preneur.
* 2:40 tu dis en 2009 pour les 20 ans du web (mais c'est pas plutôt en 2014 pour les 20 ans du W3C/25 ans du Web?) _Ah mais oui ! En fait c'est les 20 ans du W3C / 25 ans du Web. Bien vu !_
3:17 John Gruber (peut-être dire qui il est), et d'ailleurs pourquoi pas mettre les noms aussi à 2:57 ? _Bonne idée._
3:20 traduction FR en plus ? J'aurais des sous-titres Youtube en plus.

Pour la musique, c'est bien prévu ! Faut que je trouve un truc libre de droit ou que je l'enregistre moi même. (Je pars plutôt sur cette seconde idée pour le moment.)

J'ai fait [une troisième version](https://drive.google.com/open?id=1FTa9ryNagUh3sU-C6DfmaLcU_raGC102) où j'avais déjà corrigé les points ci-dessous. Du coup pour te répondre :

* 0:40 problème de son ? _En fait j'avais pas encore enregistré l'audio de ce passage._
* 3:05 je trouve l'anim pas très en phase avec le propos. Tu survoles des navigateurs, puis l'appli mail, puis Photoshop. _Oui ! J'ai réenregistré ce passage._
* 3:42 pas d'illustrations ? _C'est fait !_
* 3:56 -> 4:04 vide ? du coup est-ce utile ? ou dire qu'il y aura un épisode dédié ? _C'est bon c'est fait maintenant._
* 5:00 c'est vrai que le mot continuum est un peu confus (mais on comprends bien le discours de Jeremy). Peux-être reprendre en français, le web est une continuité ? _J'ai rajouté une phrase pour dire que le terme est pas parlant mais l'explication oui._
* 5:30 le son clic mais il manque l'icone pause _Corrigé !_
* 5:50 après le «This is for everyone. C'est pour le tout le monde», j'aurais encore plus accentué, avec un « c'est de ça dont je parlais » ou un truc du genre pour faire référence à ton «c'est pas de ça dont je parlais » ironique qq secondes avant _Yes j'avais aussi prévu ça !_

**Comment by iamvdo** [comment]
Pour la map, je connais pas Premiere. Je pensais que c'était une simple carte, en screencast ? D'ailleurs, j'ai regardé un peu et la plaque commémorative au CERN est dans le bâtiment 2 (en Suisse), même si ça parle du bâtiment 31 quand même.

Le texte de la plaque: https://www.lhc-closer.es/taking_a_closer_look_at_lhc/0.cern_where_the_web_was_born

Et des photos du couloir: https://www.atlasobscura.com/places/birthplace-of-the-web

Je regarde la v3 dès qu'elle sera uploadée.

**Comment by iamvdo** [comment]
Problèmes de son sur la v3 :(

**Comment by hteumeuleu** [comment]
Moué sur Quicktime ça foire. Mais normalement sur VLC ça passe ?

**Comment by iamvdo** [comment]
Non, ni sur le Drive, ni VLC

**Comment by hteumeuleu** [comment]
Ah, zut, bizarre ("chez moi ça marche"). Je regarde ça au prochain encodage et je remettrais une nouvelle version (surement en début de semaine).

**Comment by hteumeuleu** [comment]
Pour l'invention du Web dans le bâtiment 31, je me base sur cet article de 2012 : https://www.theverge.com/2012/1/26/2734998/tim-berners-lee-web-france-switzerland-cern

**Comment by hteumeuleu** [comment]
Et pour confirmer ta remarque : c'était bien au 20 ans du W3C (et non les 20 ans du Web) https://www.w3.org/20/

**Comment by iamvdo** [comment]
Après écoute de la v4: waouh ! C'est top.

Juste un petit truc sur la fin, je préférais l'intonation de la v1/v2 sur "Merci de votre écoute. Et bienvenue dans troisdoublev" :)

**Comment by hteumeuleu** [comment]
Fait !

**Comment by hteumeuleu** [comment]
Je ferme vu que c'est fini mais n'hésite pas à rouvrir si besoin.
